services:
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: cinephoria-backend-production.up.railway.app
      dockerfile: Dockerfile
    ports:
      - "80:80" # Permet l'accès à Nginx via le port 80
      # - "443:443" # Si tu utilises HTTPS
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
